title = "Vinoth Resume"
baseURL = "https://example.com/"
theme = "my-resume"
languageCode = "en-us"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = false

[params]
address = "Coimbatore, India"
favicon = "/favicon.ico"
firstName = "VinothKumar"
lastName = "Ramakrishnan"
phone = "1-555-555-1234"
showSocializations = true
showContact = false
sections = ["skills","publications","creations","contributions","experience","education","blog"]


[params.google]

[params.google.analytics]
trackerID = "XX-123446-01"

[[params.handles]]
link = "https://www.linkedin.com/in/sathishkumarthiyagarajan/"
name = "LinkedIn"

[[params.handles]]
link = "https://github.com/vinothcyber/"
name = "GitHub"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"
